---
- name: Deploy the Raspberry Pi PHP GPIO interface to a Pi
  hosts: mypi
  gather_facts: no
  become: yes

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      install_recommends: yes
    vars:
      packages:
      - apache2
      - php

  - name: Sync the web directory
    synchronize:
      src: files/html/
      dest: /var/www/html/
      recursive: yes
      delete: yes
    become: true
    tags:
      - html

  - name: Sync the WiringPi directory
    synchronize:
      src: files/WiringPi/
      dest: /root/WiringPi/
      recursive: yes
    become: true

  - name: Build WiringPi from source
    shell:
      cmd: ./build
      chdir: /root/WiringPi
    become: true

  - name: Remove the ugly default index.html page
    file:
      dest: /var/www/html/index.html
      state: absent

  - name: apache2 config file
    copy:
      src: files/apache2.conf
      dest: /etc/apache2/apache2.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: sudoers file for the raspi-gpio command
    copy:
      src: files/raspi-gpio-sudoers
      dest: /etc/sudoers.d/raspi-gpio
      owner: root
      group: root
      mode: '0644'

  - name: Enable mod_rewrite into apache2
    shell:
      cmd: a2enmod rewrite
    become: true

  - name: Enable apache2 service and make sure it is started
    service:
      name: apache2
      enabled: yes
      state: restarted
