---
- name: Deploy the Raspberry Pi PHP GPIO interface to a Pi
  hosts: mypi
  become: yes

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      dpkg_options: 'force-confold,force-confdef,dist-upgrade'
      install_recommends: yes
      force: yes
    vars:
      packages:
      - apache2
      - php

  - name: Sync the web directory
    synchronize:
      src: files/html/
      dest: /var/www/html/
      recursive: yes
    become: true

  - name: Sync the WiringPi directory
    synchronize:
      src: files/WiringPi/
      dest: /root/WiringPi/
      recursive: yes
    become: true

  - name: Build WiringPi from source
    shell:
      cmd: ./build
      chdir: /root/WiringPi
    become: true

  - name: Remove the ugly default index.html page
    file:
      dest: /var/www/html/index.html
      state: absent

  - name: Fix the apache2 conf to servce up index.php as the main page
    lineinfile:
      path: /etc/apache2/apache2.conf
      insertafter: '^<Directory /var/www/>'
      line: '        DirectoryIndex index.php'

  - name: Enable apache2 service and make sure it is started
    service:
      name: apache2
      enabled: yes
      state: restarted
